server:
  port : 8090
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        persons-in:
          destination: persons-topic
          contentType: application/*+avro
          group: persons-group-2
      schema:
        avro:
          schema-locations: classpath:avro/person.avsc
      schema-registry-client:
        endpoint: http://localhost:8990