version: '2'
services:
  kafka-postgresql:
    image: postgres:10.4
    hostname: postgresql
    container_name: kafka-postgresql
    networks:
      - host
    #volumes:
      #- ~/volumes/kafka/kafkapostgresql/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=inventory
    ports:
      - 5432:5432
networks:
  host:
    driver: "bridge"